In [1]:
import pandas as pd

In [7]:
pd.__version__

'3.0.3'

In [8]:
dict_medidas = {
    "idade": [15, 18, 25, 25, 40, 55, 58, 60, 80],
    "altura": [160, 162, 165, 168, 172, 174, 174, 174, 176],
}

In [9]:
dict_medidas

{'idade': [15, 18, 25, 25, 40, 55, 58, 60, 80],
 'altura': [160, 162, 165, 168, 172, 174, 174, 174, 176]}

In [10]:
df_medidas = pd.DataFrame.from_dict(dict_medidas)

In [12]:
df_medidas

   idade  altura
0     15     160
1     18     162
2     25     165
3     25     168
4     40     172
5     55     174
6     58     174
7     60     174
8     80     176

# Medidas Resumo

### Medidas de Posição

In [13]:
# media
df_medidas["idade"].mean()

np.float64(41.77777777777778)

In [15]:
# mediana
df_medidas["idade"].median()

np.float64(40.0)

In [16]:
# moda
df_medidas["idade"].mode()

0    25
Name: idade, dtype: int64

In [17]:
# moda altura
df_medidas["altura"].mode()

0    174
Name: altura, dtype: int64

### Medidas de Dispersão

In [ ]:
# variancia
# sintaxe alternativa
df_medidas.idade.var() # diferença entre a média e cada valor, elevado ao quadrado

np.float64(509.94444444444446)

In [21]:
# desvio padrão
df_medidas.idade.std() # raiz quadrada da variância

np.float64(22.58194952709895)

In [ ]:
# coeficiente de variação -idade (desvio padrão dividido pela média, multiplicado por 100 para obter o resultado em porcentagem)
df_medidas.idade.std() / df_medidas.idade.mean() * 100

np.float64(54.05253876167302)

In [24]:
# coeficiente de variação - altura
df_medidas.altura.std() / df_medidas.altura.mean() * 100

np.float64(3.4803552812368785)

### Medidas de Forma

In [25]:
# Assimetria - Idade
df_medidas.idade.skew()

np.float64(0.368108517895537)

In [26]:
# Assimetria - Altura
df_medidas.altura.skew()

np.float64(-0.598486996170113)

In [30]:
# Curtose - Idade
df_medidas.idade.kurtosis()

np.float64(-1.1344461075421046)

In [31]:
# Curtose - Altura
df_medidas.altura.kurtosis()

np.float64(-1.3372641199913002)

In [32]:
# Obter medidas estatísticas 
df_medidas.idade.describe()

count     9.000000
mean     41.777778
std      22.581950
min      15.000000
25%      25.000000
50%      40.000000
75%      58.000000
max      80.000000
Name: idade, dtype: float64

### Correlação de variáveis

In [ ]:
# Correlação do DataFrame, segundo Pearson
df_medidas.corr(method='pearson')

           idade    altura
idade   1.000000  0.931024
altura  0.931024  1.000000

In [36]:
# Correlação entre duas variáveis
df_medidas.idade.corr(df_medidas.altura, method='pearson')

np.float64(0.9310236045054339)

In [37]:
# Correlação de DataFrame, segundo Spearman
df_medidas.corr(method='spearman')

           idade    altura
idade   1.000000  0.978803
altura  0.978803  1.000000